# Generated by Django 5.2.13 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description_title',
            field=models.CharField(default='A Nature-Inspired Sanctuary', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
