# Generated by Django 5.2.13 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_description_title_hotel_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
    ]
