# Generated by Django 5.2.13 on 2026-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_image2_hotel_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
