# Generated by Django 5.2.13 on 2026-04-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_is_available_hotel_total_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_guests',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
