# Generated by Django 5.2.13 on 2026-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_max_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
